service: trpc-server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  vpc:
    securityGroupIds:
      - ${file(${self:custom.envFile}):SECURITY_GROUP}
    subnetIds:
      - ${file(${self:custom.envFile}):SUBNET_1}
      - ${file(${self:custom.envFile}):SUBNET_2}
  iam:
    deploymentRole: ${file(${self:custom.envFile}):DEPLOYMENT_ROLE}

functions:
  rest-api:
    handler: src/server.handler
    events:
      - http:
          path: /trpc/{proxy+}
          method: any
          cors: true
    environment:
      PRISMA_DATABASE_URL: ${file(${self:custom.envFile}):PRISMA_DATABASE_URL}

package:
  patterns:
    - 'src/generated/**'
  individually: true

custom:
  stage: ${opt:stage, 'local'}
  envFile: .env.${self:custom.stage}.yml
  esbuild:
    watch:
      pattern: './src/**/*.ts'

plugins:
  - serverless-esbuild
  - serverless-offline
